# Atuin Configuration for YouTube Channel Setup
# Enhanced shell history with search and sync capabilities

## where to store your database, default is your system data directory
## macOS: ~/Library/Application Support/atuin/history.db
# db_path = "~/.local/share/atuin/history.db"

## where to store your encryption key, default is your system data directory
# key_path = "~/.local/share/atuin/key"

## where to store your auth session token, default is your system data directory  
# session_path = "~/.local/share/atuin/session"

## date format used, either "us" or "uk"
dialect = "us"

## enable or disable automatic sync
auto_sync = true

## enable or disable automatic update checking
update_check = true

## address of the sync server
sync_address = "https://api.atuin.sh"

## how often to sync history. note that this is only triggered on a shell command
## being run, so sync intervals may be longer
## set it to 0 to sync after every command
sync_frequency = "10m"

## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
search_mode = "fuzzy"

## which filter mode to use
## possible values: global, host, session, directory
filter_mode = "global"

## With workspace filtering enabled, Atuin will filter for commands executed
## in any directory that is a child of the workspace root.
## Defaults to false
workspaces = false

## which style to use
## possible values: auto, full, compact
style = "auto"

## the maximum number of lines the interface should take up
## set it to 0 to always go full screen
inline_height = 0

## enable or disable showing a preview of the selected command
## useful when the command is longer than the terminal width and is cut off
show_preview = true

## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
exit_mode = "return-original"

## possible values: emacs, subl
word_jump_mode = "emacs"

## characters that count as a part of a word
word_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## number of context lines to show when scrolling by pages
scroll_context_lines = 1

## use ctrl instead of alt as the shortcut modifier key for numerical UI shortcuts
## alt-0 .. alt-9
ctrl_n_shortcuts = false

## default history list format - can also be specified with the --format arg
history_format = "{time}\t{command}\t{duration}"

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
history_filter = [
    "^secret-cmd",
    "^password",
    "^token",
    "^key",
    "^auth",
    "^login",
    "^sudo",
]

## prevent commands run with cwd matching any of these regexes from being written
## to history. Note that these regular expressions are unanchored, i.e. if they don't
## start with ^ or end with $, they'll match anywhere in the command.
cwd_filter = [
    "^/tmp",
]

## configure whether or not to show the help row, which includes the current Atuin
## version (and whether an update is available), a keymap hint, and the total
## amount of commands in your history
show_help = true

## configure whether or not to show tabs for search and inspect
show_tabs = true

## defaults to true
## enable or disable showing the current directory when listing history
show_time = true

## defaults to false
## enable or disable showing the current directory when listing history  
show_exit = false

## defaults to true
## enable or disable showing the command duration when listing history
show_duration = true

## Defaults to false
## This matches history against a set of default regex, and will not save these
## to history. Defaults to true.
secrets_filter = true

## Defaults to true
## Set this to false and Atuin won't try to use the keyring for storing credentials
use_keyring = true

## Defaults to "keyring"
## This allows you to select a different keyring backend.
## Possible values: "keyring", "linux", "macos", "windows"
keyring_backend = "keyring"

## Defaults to false
## Enable this and Atuin will record the time that every command took to run
record_time = true

## Defaults to false
## Enable this and Atuin will use the prefers_reduced_motion setting
prefers_reduced_motion = false

## Defaults to false
## This enables a periodic sync of history. Every sync_frequency, Atuin will
## automatically sync history - but only if a command has been run in the meantime.
periodic_sync = false

## Defaults to false
## This enables vim mode for the search
vim_mode = false

## Defaults to 8
## This sets the maximum number of lines that the TUI will show for a command
max_preview_height = 8

## Defaults to 0
## This sets the maximum number of chars that the TUI will show for a command
max_preview_width = 0

## Defaults to false
## This enables the blazingly fast displaying of search results.
## When enabled, search results are shown as soon as they are available.
## When disabled, search results are shown after the search is complete.
## This is useful for large histories, but may cause some visual artifacts.
enter_accept = true